apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.microserviceName}}-service"
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.microserviceName}}
  ports:
  - port: {{.Values.service.port}}
    targetPort: {{.Values.container.port}}