apiVersion: apps/v1
kind: Deployment
metadata:
  name: playidentity-deployement
spec:
  selector:
    matchLabels:
      app: playidentity
  template:
    metadata:
      labels:
        app: playidentity
    spec:
      serviceAccountName: playidentity-serviceaccount
      containers:
      - name: playidentity
        image: playeconomyazurecontainerregistry.azurecr.io/play.identity:1.0.11
        env:
          - name: ServiceSettings__MessageBroker
            value: AZURESERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: playeconomyazurekeyvault
          # - name: MongoDbSettings__ConnectionString
          #   valueFrom:
          #     secretKeyRef:
          #       name: playidentity-secrets
          #       key: cosmosdb-connectionstring
          # - name: ServiceBusSettings__ConnectionString
          #   valueFrom:
          #     secretKeyRef:
          #       name: playidentity-secrets
          #       key: servicebus-connectionstring
          # - name: IdentitySettings__AdminUserPassword
          #   valueFrom:
          #     secretKeyRef:
          #       name: playidentity-secrets
          #       key: admin-password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5229
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5229
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5229
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: playidentity-service
spec:
  type: LoadBalancer
  selector:
    app: playidentity
  ports:
  - port: 80
    targetPort: 5229
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: playidentity-serviceaccount
  annotations: 
    azure.workload.identity/client-id: 909418d1-303c-4b2c-8b54-10924b504c34
  labels:
    azure.workload.identity/use: "true"