apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playidentity-signing-cert
spec:
  secretName: playidentity-signing-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "playeconomygateway.eastus.cloudapp.azure.com"